platform :ios, '8.0'
use_frameworks!

# http://stackoverflow.com/questions/37613550/xcode-error-itms-90635-invalid-mach-o-in-bundle-submitting-to-app-store/37624641#37624641
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

pod 'JSONModel'
pod 'ObjectMapper'
#pod 'UIScrollView-InfiniteScroll'
#pod 'ALCameraViewController'
#pod 'PagingMenuController'
#pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#pod 'SwiftEventBus', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
pod 'SwiftEventBus', :tag => '1.1.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
pod 'Alamofire', '~> 3.0'
pod 'AlamofireObjectMapper', '~> 2.0'
pod 'Kingfisher', '~> 1.9.3'
pod 'PhotoSlider', '~> 0.12.1'
pod 'PullToRefreshSwift', '~> 2.0.0'
pod 'AMScrollingNavbar', '~> 2.0.1'
pod 'QQPlaceholderTextView', '~> 0.0.2'
pod 'BetterSegmentedControl', '0.4'
pod 'XMSegmentedControl', '~> 0.1.4'
pod 'Cosmos', '~> 1.2'